name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
  workflow_call:

permissions: write-all

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
       dotnet-version: '10.0.x'
       
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet restore . -p:EnableWindowsTargeting=true

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      ###run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /t:Publish
      ##run: dotnet build . -c Release -p:EnableWindowsTargeting=truendows Executable
      run: | 
        dotnet build . -c Release -p:EnableWindowsTargeting=true -r win-x64 -p:ImportByWildcardBeforeSolution=false -o ./build
        dotnet publish ${{ github.workspace }}/NHSE.WinForms/NHSE.WinForms.csproj -c Release -p:EnableWindowsTargeting=true -r win-x64 --self-contained true -p:PublishSingleFile=true -p:ImportByWildcardBeforeSolution=false -o ./publish 
        
    - name: Create Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ github.token }} 
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.run_number }}
        body: ${{ github.event.head_commit.message }}

    ###D:\a\NHSE\NHSE\NHSE.WinForms\bin\Release\net10.0-windows\publish\
    ###zip -r ${{ github.workspace }}/linux-release.zip .
    # - name: Zipping up Release folder
      # run: | 
        # cd ${{ github.workspace }}/publish
        # zip -r ${{ github.workspace }}/NHSE.zip .
             
    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false    
        tag_name: ${{ github.run_number }}
        body: ${{ github.event.head_commit.message }}
        files: ${{ github.workspace }}/publish/NHSE.WinForms.exe
      env:
        GITHUB_TOKEN: ${{ github.token }}
        